### PR TITLE
Chore: Adjust Project

### PR DESCRIPTION
**Pull request by riandyrn**
Changes summary:

- Rename package to `github.com/Haraj-backend/go-sse`
- Include `Haraj-backend` authors to `LICENSE`
- Move CI pipeline to Github Action instead TravisCI
- Update links in `README.md` to `github.com/Haraj-backend/go-sse`

### CODE REVIEW

**Review by harunalfat — APPROVED** [review]
Nicee, LGTM 💯

**Comment by riandyrn** [comment]
Any comments, @knightazura, @isdzulqor?

**Review by knightazura — APPROVED** [review]
Looks good 📦

**Review by isdzulqor — APPROVED** [review]
LGTM 🎉 🎉 🎉

**Pull request merged**
